name: Push Hydro Image to ACR

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (not strictly needed)
        uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            ${{ secrets.ACR_REGISTRY }} \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} \
            --password-stdin


      - name: Pull Hydro official image
        run: |
          docker pull ghcr.io/hydro-dev/hydro:latest



      - name: Tag image for ACR
        run: |
          docker tag ghcr.io/hydro-dev/hydro:latest \
           ${{ secrets.ACR_REGISTRY }}/hydro_oj/hydro_oj:latest


      - name: Push image to ACR
        run: |
          docker push \
            ${{ secrets.ACR_REGISTRY }}/hydro_oj/hydro_oj:latest
